import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  const body = await request.json()
  const { videoId, message } = body

  if (!videoId || !message) {
    return NextResponse.json({ error: 'Missing videoId or message' }, { status: 400 })
  }

  // Here you would typically call your AI service to generate a response
  // For this example, we'll return a mock response
  const response = `This is a mock AI response for video ID: ${videoId} and message: "${message}". In a real application, this would be generated by an AI service based on the video content and the user's message.`

  return NextResponse.json({ response })
}

